#!/bin/bash

echo "push to location: ${ONEDRIVE}Notes"

if [ ! -d ${ONEDRIVE}Notes/electron ] 
then
  mkdir ${ONEDRIVE}Notes/electron
fi
cp electron/*.pdf ${ONEDRIVE}Notes/electron/


if [ ! -d ${ONEDRIVE}Notes/phonon ]
then
  mkdir ${ONEDRIVE}Notes/phonon
fi
cp phonon/*.pdf ${ONEDRIVE}Notes/phonon/

if [ ! -d ${ONEDRIVE}Notes/statistic ] 
then
  mkdir ${ONEDRIVE}Notes/statistic
fi
cp statistic/*.pdf ${ONEDRIVE}Notes/statistic/

echo "Done"
